USE farmaciaglorys;

/*Diseño Físico del Data Mart*/
/*Tabla HECHOS*/
CREATE TABLE H_VENTAS (
ID_VENTA INT PRIMARY KEY,
ID_TIEMPO INT,
ID_PRODUCTO INT,
ID_CLIENTE INT,
ID_EMPLEADO INT,
UNIDADES_V DOUBLE(8,2),
PRECIO DECIMAL(8,2),
TOTAL_V DECIMAL(8,2)
);

/*Tabla de Dimesión de Producto*/
CREATE TABLE DIM_PRODUCTO (
ID_PRODUCTO INT PRIMARY KEY,
NOM_PRODUCTO VARCHAR(30),
DESCRIPCION VARCHAR(200),
PRECIO DECIMAL (8,2),
MARCA VARCHAR(20),
CATEGORIA VARCHAR(20),
PRESENTACION VARCHAR(20)
);

/*Tabla de Dimensión de Cliente*/
CREATE TABLE DIM_CLIENTE (
ID_CLIENTE INT PRIMARY KEY,
NOMBRE_C VARCHAR(20),
TELEFONO VARCHAR(8),
CORREO NVARCHAR(30)
);

/*Tabla de Dimensión de Empleado*/
CREATE TABLE DIM_EMPLEADO (
ID_EMPLEADO INT PRIMARY KEY,
NOMBRE_E VARCHAR(20)
);

/*Tabla de Dimensión de Tiempo*/
CREATE TABLE DIM_TIEMPO (
ID_TIEMPO INT PRIMARY KEY,
FECHA INT(2),
AÑO INT(4),
MES INT(2),
DIA INT(10)
);

/*Relaciones entre tablas*/
ALTER TABLE H_VENTAS ADD CONSTRAINT FK_DIM_PRODUCTO_H_VENTAS FOREIGN KEY (ID_PRODUCTO) REFERENCES DIM_PRODUCTO(ID_PRODUCTO);
ALTER TABLE H_VENTAS ADD CONSTRAINT FK_DIM_CLIENTE_H_VENTAS FOREIGN KEY (ID_CLIENTE) REFERENCES DIM_CLIENTE(ID_CLIENTE);
ALTER TABLE H_VENTAS ADD CONSTRAINT FK_DIM_EMPLEADO_H_VENTAS FOREIGN KEY (ID_EMPLEADO) REFERENCES DIM_EMPLEADO(ID_EMPLEADO);
ALTER TABLE H_VENTAS ADD CONSTRAINT FK_DIM_TIEMPO_H_VENTAS FOREIGN KEY (ID_TIEMPO) REFERENCES DIM_TIEMPO(ID_TIEMPO);